services:
  db:
    image: postgres:15-alpine
    container_name: hospital-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - hospital_postgres_data:/var/lib/postgresql/data

volumes:
  hospital_postgres_data:
